import React from 'react';

import AddressShow from '../components/AddressShow';
import { configure, shallow } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import AddressList from '../address-list';
import AppBar from '@material-ui/core/AppBar';
import Drawer from '@material-ui/core/Drawer';
import MenuItem from '@material-ui/core/MenuItem';

configure({ adapter: new Adapter() });

describe('AddressShow Shallow Suite', function() {
    const debug = false;

    /*
     * Display debug information about a DOM node of a component by index
     * @param {object} wrapper - The HTML generated by your component
     * @param {number} index - Index of HTML element you want to see.
     * @param {boolean} talkToMe - Speak even if quiet is true
     */
    const getIndex = (wrapper, index, talkToMe) => {
        if (debug || talkToMe) {
            const ninep = wrapper
                .find('div#addressShow')
                .childAt(index)
                .debug();
            console.log('NINEP:', ninep);
        }
    };

    const defaultFieldTest = (name, index, talkToMe) => {
        const wrapper = shallow(<AddressShow address={AddressList[0]} />);
        const welcome = <p className="App-intro">{name}</p>;
        //console.log(welcome);
        getIndex(wrapper, index, talkToMe);
        expect(wrapper.contains(welcome)).toEqual(true);
    };

    const afterClickFieldTest = (name, index, talkToMe) => {
        const wrapper = shallow(<AddressShow address={AddressList[1]} />);
        const welcome = <p className="App-intro">{name}</p>;
        //   console.log("being passed: ", name);
        getIndex(wrapper, index, talkToMe);
        expect(wrapper.contains(welcome)).toEqual(true);
    };

    // this is looking for an id on a button.  Give it one.
    fit('handles click on foobar with enzyme', () => {
        const wrapper = shallow(<AddressShow />);
        console.log(wrapper.debug());
        wrapper.find('#fetchAddresses').simulate('click');
        expect(wrapper).toMatchSnapshot();
    });

    it('renders and displays the first name', () => {
        defaultFieldTest('First Name: unknown', 0);
        afterClickFieldTest('First Name: ' + AddressList.firstName, 0);
    });

    it('renders and displays the last name', () => {
        defaultFieldTest('Last Name: unknown', 0);
        afterClickFieldTest('Last Name: ' + AddressList.lastName, 0);
    });

    it('renders and displays the address', () => {
        defaultFieldTest('Address: unknown', 0);
        afterClickFieldTest('Address: ' + AddressList.address, 0);
    });

    it('renders and displays the address', () => {
        //const addressTestValue = <p className="App-intro">'Address: unknown'</p>
        defaultFieldTest('Address: unknown', 0);
        afterClickFieldTest('Address: 154 Wiseguy Ave', 0);
    });

    it('renders and displays the city', () => {
        defaultFieldTest('City: unknown', 0);
        afterClickFieldTest('City: ' + AddressList.city, 0);
    });

    it('renders and displays the state', () => {
        defaultFieldTest('State: unknown', 0);
        afterClickFieldTest('State: ' + AddressList.state, 0);
    });

    it('renders and displays the zip', () => {
        defaultFieldTest('Zip: unknown', 0);
        afterClickFieldTest('Zip: ' + AddressList.zip, 0);
    });
    it('renders and displays the phone', () => {
        defaultFieldTest('Phone: unknown', 0);
        afterClickFieldTest('Phone: ' + AddressList.phone, 0);
    });
    it('renders and displays the fax', () => {
        defaultFieldTest('Fax: unknown', 0);
        afterClickFieldTest('Fax: ' + AddressList.fax, 0);
    });
    it('renders and displays the tollfree', () => {
        defaultFieldTest('Toll Free: unknown', 0);
        afterClickFieldTest('Toll Free: ' + AddressList.tollfree, 0);
    });
    // EVENTUALLY YOU WILL NEED TO WRITE MORE TESTS LIKE THE FIRST NAME TEST.
    // THE GOAL WILL BE TO TEST ALL THE PROPERTIES OF OUR COMPONENT.
    // AT FIRST, HOWEVER, JUST KEEP THESE TWO TESTS. WHEN THEY START
    // PASSING, THEN ADD TESTS FOR THE OTHER PROPERTIES SUCH AS LASTNAME...
});
